// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	model "8_mockery/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserDB is an autogenerated mock type for the UserDB type
type UserDB struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, u
func (_m *UserDB) Save(ctx context.Context, u *model.User) error {
	ret := _m.Called(ctx, u)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
